name: Install dependencies
description: Install NPM dependencies after installing any missing system library dependencies.
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      id: pnpm-install
      with:
        run_install: false

    - name: Install node.js version
      uses: actions/setup-node@v4
      id: install-node
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Install dependencies
      shell: bash
      run: pnpm install

